logging:
  level:
    org:
      springframework: trace
    root: info
server:
  port: '8080'
spring:
  profiles:
    active: local
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis